package com.bawei.chengxiaoyue20200106.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.chengxiaoyue20200106.dao.LeftTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEFT_TABLE".
*/
public class LeftTableDao extends AbstractDao<LeftTable, Void> {

    public static final String TABLENAME = "LEFT_TABLE";

    /**
     * Properties of entity LeftTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property LeftDatabase = new Property(0, String.class, "LeftDatabase", false, "LEFT_DATABASE");
    }


    public LeftTableDao(DaoConfig config) {
        super(config);
    }
    
    public LeftTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEFT_TABLE\" (" + //
                "\"LEFT_DATABASE\" TEXT);"); // 0: LeftDatabase
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEFT_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LeftTable entity) {
        stmt.clearBindings();
 
        String LeftDatabase = entity.getLeftDatabase();
        if (LeftDatabase != null) {
            stmt.bindString(1, LeftDatabase);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LeftTable entity) {
        stmt.clearBindings();
 
        String LeftDatabase = entity.getLeftDatabase();
        if (LeftDatabase != null) {
            stmt.bindString(1, LeftDatabase);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LeftTable readEntity(Cursor cursor, int offset) {
        LeftTable entity = new LeftTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // LeftDatabase
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LeftTable entity, int offset) {
        entity.setLeftDatabase(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LeftTable entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LeftTable entity) {
        return null;
    }

    @Override
    public boolean hasKey(LeftTable entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
